#' A wrapper function for running AquaCrop for use in CroptimizR package
#'
#' `aquacrop_wrapper` takes parameter values as an input for an AquaCrop simulation and returns a result list as requested by the
#' `CroptimizR` package.
#' `r lifecycle::badge('experimental')`
#' @import dplyr
#' @import purrr
#' @import readr
#' @param param_values list of crop parameters to modify from the default
#' @param situation character vector of scenario names as listed in the Scenario_s tibble
#' @param model_options list of model options: `AQ` is the aquacrop path as generated by the `path_config` function,
#' `cycle_length` an integer representing the length of the **simulation** period in days, `growth_length` an integer representing the length of the **growth** period in days, `defaultpar` is the default parameter list as designed by the `read_CRO` function,
#' `output` defines the shape of the output that is returned and `daily_output` defines the daily output variables that are generated by AquaCrop.
#' @returns a dataframe or list (if `model_options$output` = 'croptimizr') of daily outputs of AquaCrop, concatenated over the different scenario's.
#'
#' @examples
#'
#' \dontrun{y <- aquacrop_wrapper(param_values = params,
#'                       situation = Scenario_s$Scenario,
#'                       model_options = list(AQ=AQ, defaultpar=Spinach,
#'                                            output = "croptimizr", daily_output = c(1,2)))}
#'
#' @export
aquacrop_wrapper <- function(param_values,
                             situation,
                             model_options=list(AQ = AQ, cycle_length = 70, growth_length = NULL,
                                                defaultpar=Spinach, output = 'croptimizr',
                                                daily_output = c(1,2)),
                             ...){


  AQ <- normalizePath(AQ, "/")
  #check the required initial steps
  if(!tail(str_split_1(AQ, "/"), 1) %in% c("aquacrop", "aquacrop.exe")) stop("Executable file should be aquacrop.exe (Windows) or aquacrop (Linux)")
  if(!dir.exists("DATA/")) stop("run the path_config function first")
  #if(!exists(quote(model_options$defaultpar))) stop("the default parameter file is not loaded, use the read_CRO function first")

  unlink("OUTP/*")
  unlink("LIST/*")

  growth_length <- ifelse(is.null(model_options$growth_length), model_options$cycle_length, model_options$growth_length)
  if(growth_length > model_options$cycle_length) stop("growth_length should not be larger than cycle_length")


  # Create crop parameter file
  cycle_info <- write_CRO(as.list(param_values), model_options$defaultpar)
  write_lines(model_options$daily_output, file = "SIMUL/DailyResults.SIM")

  # create project, meteo, soil, management,... files
  createfiles(Exp_list = situation, cycle_length = model_options$cycle_length)

  situation %>%
    purrr::walk(~checkInputdata(Scenario_ = .x, cycle_info, model_options$cycle_length))

  ###########################################
  # Run Aquacrop for all the created projects

  system(model_options$AQ)

  #############
  # Read output
  results <- list.files("OUTP/", pattern = "PROday.OUT", full.names = F) %>%
    purrr::map(\(x) readoutput_dfr(x, cycle_length = model_options$cycle_length,
                                   growth_length = growth_length,
                                   daily_output = model_options$daily_output))

  if (model_options$output == 'croptimizr'){
    results <- results %>%
      set_names(situation)
    results <- list(sim_list = results, error = FALSE)
    attr(results$sim_list, "class") <- "cropr_simulation"
  } else {
    results <- results %>%
      list_rbind()
  }

#
# if (model_options$output == 'croptimizr'){
#   results <- list.files("OUTP/", pattern = "PROday.OUT", full.names = F) %>%
#     purrr::map(~readoutput_croptimizr(.x, cycle_length = model_options$cycle_length,
#                                       daily_output = model_options$daily_output)) %>%
#     set_names(situation)
#   results <- list(sim_list = results, error = FALSE)
#   attr(results$sim_list, "class") <- "cropr_simulation"
#
# } else {
#   if (model_options$output == 'morris') {
#     results <- list.files("OUTP/", pattern = "PROday.OUT", full.names = F) %>%
#       purrr::map_dfr(~readoutput_morris(.x, cycle_length = model_options$cycle_length,
#                                         daily_output = model_options$daily_output))
#   } else{
#     results <- list.files("OUTP/", pattern = "PROday.OUT", full.names = F) %>%
#       purrr::map_dfr(~readoutput_dfr(.x, cycle_length = model_options$cycle_length,
#                                      daily_output = model_options$daily_output))
#   }
# }


  return(results)
}
#'



readoutput_dfr <- function(outputfile, cycle_length, growth_length, daily_output){

  sit_name <- gsub("PROday.OUT", "", outputfile)
  soil_prof <- (SOL_s %>%
                  dplyr::filter(ID == (Scenario_s %>% dplyr::filter(Scenario == sit_name) %>% .$Soil)) %>%
                  .$Thickness %>% sum() * 10) %>%
    ceiling
  df <- readr::read_fwf(file = paste0("OUTP/", outputfile),  skip = 4, show_col_types = F)
  names(df) <- varnames_fun(daily_output, soil_prof)

  allnames <- varnames_fun(daily_output, 12)
  new_columns <- setdiff(allnames, names(df))

  for (col in new_columns){
    df[[col]] <- NA
  }

  df <- df %>%
    dplyr::select(allnames) %>%
    dplyr::select(which(!duplicated(names(.)))) %>%
    # dplyr::filter(DAP >= 0) %>%
    dplyr::mutate(Scenario = sit_name,
                  Date = as_date(paste(Year, Month, Day , sep = "-")),
                  DOY = yday(Date),
                  GDD = cumsum(GD)) %>%
    group_by(Scenario, Stage) %>%
    mutate(Stage_c = if_else(Stage == 0, 5.0, (GDD - min(GDD))/(max(GDD) - min(GDD)) + Stage)) %>%
    ungroup() %>%
    group_by(Scenario) %>%
    mutate(ind_DAP =which(Stage_c == 1.00)[1]) %>%
    filter(row_number() >= unique(ind_DAP) & row_number() < (unique(ind_DAP) + growth_length)) %>%
    mutate(DAP_adj = 1:growth_length) %>%
    ungroup()

  if(has_name(df, "Biomass")){
    df <- df %>%
      mutate(Biomass_Stem = (Biomass - Ydry)*0.86)
  }

  if(has_name(df, c("WC01", "WC02", "WC03")) %>% all()){
    df <- df %>%
      mutate(WC0030 = (WC01 + WC02 + WC03)/3)
  }

  return(df)
}



