#' A wrapper function for running AquaCrop for use in CroptimizR package
#'
#' `aquacrop_wrapper` takes parameter values as an input for an AquaCrop simulation and returns a result list as requested by the
#' `CroptimizR` package.
#' `r lifecycle::badge('experimental')`
#' @import dplyr
#' @import purrr
#' @import readr
#' @param param_values list of crop parameters to modify from the default
#' @param situation character vector of scenario names as listed in the Scenario_s tibble
#' @param cycle_length an integer representing the length of the **simulation** period in days
#' @param model_options list of model options: `AQ` is the aquacrop path as generated by the `path_config` function,
#' `defaultpar` is the default parameter list as designed by the `read_CRO` function and
#' `output` defines the shape of the output that is returned.
#' @returns a dataframe or list (if `model_options$output` = 'croptimizr') of daily outputs of AquaCrop, concatenated over the different scenario's.
#'
#' @examples
#'
#' y <- aquacrop_wrapper(param_values = params,
#'                      model_options = list(AQ=AQ, defaultpar=Spinach, output = "df"))
#'
#' @export
aquacrop_wrapper <- function(param_values,
                             situation,
                             cycle_length,
                             model_options=list(AQ = AQ, defaultpar=Spinach, output = 'croptimizr'),
                             ...){



  #check the required initial steps
  if(!file.exists("aquacrop.exe")){
    stop("set your working directory to the AquaCrop.path")
  }
  if(!dir.exists("DATA/")) stop("run the path_config function first")
  #if(!exists(quote(model_options$defaultpar))) stop("the default parameter file is not loaded, use the read_CRO function first")


  # Create crop parameter file
  cycle_info <- write_CRO(as.list(param_values), model_options$defaultpar)
  # for now, the Ground Water Table is fixed
  # create project, meteo, soil, management,... files
  createfiles(Exp_list = situation, cycle_length = cycle_length)

  situation %>%
    purrr::walk(~checkInputdata(Scenario_ = .x, cycle_info, cycle_length))

  ###########################################
  # Run Aquacrop for all the created projects

  system(model_options$AQ)

  #############
  # Read output
if (model_options$output == 'croptimizr'){
  # results <-
  #   list(
  #     sim_list =
  #       setNames(
  #         vector("list", length(situation)),
  #         nm = situation
  #       ),
  #     error = FALSE
  #   )

  results <- list.files("OUTP/", pattern = "PROday.OUT", full.names = F) %>%
    purrr::map(~readoutput_croptimizr(.x, cycle_length = cycle_length)) %>%
    set_names(situation)
  results <- list(sim_list = results, error = FALSE)
  attr(results$sim_list, "class") <- "cropr_simulation"

} else {
  if (model_options$output == 'morris') {
    results <- list.files("OUTP/", pattern = "PROday.OUT", full.names = F) %>%
      purrr::map_dfr(~readoutput_morris(.x, cycle_length = cycle_length))
  } else{
    results <- list.files("OUTP/", pattern = "PROday.OUT", full.names = F) %>%
      purrr::map_dfr(~readoutput_dfr(.x, cycle_length = cycle_length))
  }
}

  unlink("OUTP/*")
  unlink("LIST/*")

  return(results)
}
#'







readoutput_dfr <- function(outputfile, cycle_length){
  df <- readr::read_fwf(file = paste0("OUTP/", outputfile),  skip = 4 )
  names(df) <- readr::read_lines(file = paste0("OUTP/", outputfile),  skip = 2, n_max = 1) %>%
    str_split_1(pattern = "\ +") %>% .[-1]
  df <- df %>%
    dplyr::select(which(!duplicated(names(.)))) %>%
    # dplyr::filter(DAP >= 0) %>%
    dplyr::mutate(Scenario = gsub("PROday.OUT", "", outputfile),
                  DAP_morris = 1:cycle_length,
                  date = paste(Year, Month, Day ,"-") %>% as_date(),
                  DOY = yday(date),
                  GDD = cumsum(GD)) %>%
    group_by(Stage) %>%
    mutate(Stage_c = (GDD - min(GDD))/(max(GDD) - min(GDD)) + Stage) %>%
    ungroup()
  names(df) <- gsub("[()/.]", "S", names(df))
  return(df)
}

readoutput_morris <- function(outputfile, cycle_length){
  df <- readr::read_fwf(file = paste0("OUTP/", outputfile),  skip = 4 )
  names(df) <- readr::read_lines(file = paste0("OUTP/", outputfile),  skip = 2, n_max = 1) %>%
    str_split_1(pattern = "\ +") %>% .[-1]
  df <- df %>%
    dplyr::select(which(!duplicated(names(.)))) %>%
    dplyr::mutate(Scenario = gsub("PROday.OUT", "", outputfile),
                  DAP_morris = 1:cycle_length,
                  date = paste(Year, Month, Day ,"-") %>% as_date(),
                  DOY = yday(date),
                  GDD = cumsum(GD)) %>%
    group_by(Stage) %>%
    mutate(Stage_c = (GDD - min(GDD))/(max(GDD) - min(GDD)) + Stage) %>%
    ungroup()
  names(df) <- gsub("[()/.]", "S", names(df))
  return(df)
}

readoutput_croptimizr <- function(outputfile, cycle_length){
  df <- readr::read_fwf(file = paste0("OUTP/", outputfile),  skip = 4 )
  names(df) <- readr::read_lines(file = paste0("OUTP/", outputfile),  skip = 2, n_max = 1) %>%
    str_split_1(pattern = "\ +") %>% .[-1]
  df <- df %>%
    dplyr::select(which(!duplicated(names(.)))) %>%
    # dplyr::filter(DAP >= 0) %>%
    dplyr::mutate(Scenario = gsub("PROday.OUT", "", outputfile),
                  DAP_morris = 1:cycle_length,
                  Date = paste(Year, Month, Day ,"-") %>% as_date(),
                  DOY = yday(Date),
                  GDD = cumsum(GD)) %>%
    group_by(Stage) %>%
    mutate(Stage_c = (GDD - min(GDD))/(max(GDD) - min(GDD)) + Stage) %>%
    ungroup()
  names(df) <- gsub("[()/.]", "S", names(df))
  df <- df %>%
    mutate(Biomass_Stem = (Biomass - YSdryS)*0.86)
  return(df)

}




