#' A wrapper function for running AquaCrop for use in CroptimizR package
#'
#' `aquacrop_wrapper` takes parameter values as an input for an AquaCrop simulation and returns a result list as requested by the
#' `CroptimizR` package.
#' `r lifecycle::badge('experimental')`
#' @import dplyr
#' @import purrr
#' @import readr
#' @param param_values list of crop parameters to modify from the default
#' @param situation character vector of scenario names as listed in the Scenario_s tibble
#' @param cycle_length an integer representing the length of the **simulation** period in days
#' @param model_options list of model options: `AQ` is the aquacrop path as generated by the `path_config` function,
#' `defaultpar` is the default parameter list as designed by the `read_CRO` function and
#' `output` defines the shape of the output that is returned.
#' @returns a dataframe or list (if `model_options$output` = 'croptimizr') of daily outputs of AquaCrop, concatenated over the different scenario's.
#'
#' @examples
#'
#' y <- aquacrop_wrapper(param_values = params,
#'                      model_options = list(AQ=AQ, defaultpar=Spinach, output = "df"))
#'
#' @export
aquacrop_wrapper <- function(param_values=list(),
                             situation = "S_01",
                             cycle_length,
                             model_options=list(AQ = AQ, defaultpar=Spinach, output = 'croptimizr'),
                             ...){



  #check the required initial steps
  if(!file.exists("aquacrop.exe")){
    stop("set your working directory to the AquaCrop.path")
  }
  if(!dir.exists("DATA/")) stop("run the Path_config function first")
  #if(!exists(quote(model_options$defaultpar))) stop("the default parameter file is not loaded, use the read_CRO function first")


  # Create crop parameter file
  write_CRO(as.list(param_values), model_options$defaultpar)
  # for now, the Ground Water Table is fixed
  GWT <- 2.0
  # create project, meteo, soil, management,... files
  createfiles(Exp_list = situation, cycle_length = cycle_length, GWT = GWT)

  ###########################################
  # Run Aquacrop for all the created projects

  system(model_options$AQ)

  #############
  # Read output
if (model_options$output == 'croptimizr'){
  results <-
    list(
      sim_list =
        setNames(
          vector("list", length(situation)),
          nm = situation
        ),
      error = FALSE
    )
  attr(results$sim_list, "class") <- "cropr_simulation"
  results <- list.files("OUTP/", pattern = "PROday.OUT", full.names = F) %>%
    purrr::map(~readoutput_croptimizr(.x)) %>%
    set_names(situation)

} else {
  if (model_options$output == 'morris') {
    results <- list.files("OUTP/", pattern = "PROday.OUT", full.names = F) %>%
      purrr::map_dfr(~readoutput_morris(.x))
  } else{
  results <- list.files("OUTP/", pattern = "PROday.OUT", full.names = F) %>%
    purrr::map_dfr(~readoutput_dfr(.x))
}

  unlink("OUTP/*")
  unlink("LIST/*")

  return(results)
}
#'







readoutput_dfr <- function(outputfile){
  df <- readr::read_table(file = paste0("OUTP/", outputfile),  skip = 4, col_names = F)
  names(df) <- readr::read_table(file = paste0("OUTP/", outputfile),  skip = 2, col_names = F)[1,]
  df <- df %>%
    dplyr::select(which(!duplicated(names(.)))) %>%
    dplyr::mutate(Scenario = gsub("PROday.OUT", "", outputfile)) %>%
    dplyr::filter(DAP >= 0)
  names(df) <- gsub("[()/.]", "S", names(df))
  return(df)
}

readoutput_morris <- function(outputfile){
  df <- readr::read_table(file = paste0("OUTP/", outputfile),  skip = 4, col_names = F)
  names(df) <- readr::read_table(file = paste0("OUTP/", outputfile),  skip = 2, col_names = F)[1,]
  df <- df %>%
    dplyr::select(which(!duplicated(names(.)))) %>%
    dplyr::mutate(Scenario = gsub("PROday.OUT", "", outputfile))
  names(df) <- gsub("[()/.]", "S", names(df))
  return(df)
}

readoutput_croptimizr <- function(outputfile){
  df <- readr::read_table(file = paste0("OUTP/", outputfile),  skip = 4, col_names = F)
  names(df) <- readr::read_table(file = paste0("OUTP/", outputfile),  skip = 2, col_names = F)[1,]
  df <- df %>%
    dplyr::select(which(!duplicated(names(.)))) %>%
    dplyr::filter(DAP >= 0)
  return(df)

}




