#' A wrapper function for running AquaCrop and only keep seasonal results
#'
#' `aquacrop_season` takes parameter values as an input for an AquaCrop simulation and returns seasonal values.
#' `r lifecycle::badge('experimental')`
#' @import dplyr
#' @import purrr
#' @import readr
#' @param param_values list of crop parameters to modify from the default
#' @param situation character vector of scenario names as listed in the Scenario_s tibble
#' @param model_options list of model options: `AQ` is the aquacrop path as generated by the `path_config` function,
#' `cycle_length` an integer representing the length of the **simulation** period in days, `growth_length` an integer representing the length of the **growth** period in days, `defaultpar` is the default parameter list as designed by the `read_CRO` function,
#' `output` defines the shape of the output that is returned and `daily_output` defines the daily output variables that are generated by AquaCrop.
#' @returns a dataframe or list (if `model_options$output` = 'croptimizr') of daily outputs of AquaCrop, concatenated over the different scenario's.
#'
#' @examples
#'
#' \dontrun{y <- aquacrop_season(param_values = params,
#'                       situation = Scenario_s$Scenario,
#'                       model_options = list(AQ=AQ, defaultpar=Spinach,
#'                                            output_type = "croptimizr", output_vars = c(1,2)))}
#'
#' @export
write_scenario_files <- function(situation, output_vars = c(1,2),
                                 cycle_length = 70, growth_length = NULL,...){

  if(!dir.exists("DATA/")) stop("run the path_config function first")
  growth_length <- ifelse(is.null(growth_length), cycle_length, growth_length)
  if(growth_length > model_options$cycle_length) stop("growth_length should not be larger than cycle_length")

  unlink("LIST/*")
  unlink("DATA/*")

  # write file that defines output variables
  write_lines(model_options$output_vars, file = "SIMUL/DailyResults.SIM")

  # create project, meteo, soil, management,... files
  createfiles(Exp_list = situation, cycle_length = cycle_length)
  assign(cycle_length, cycle_length)
}

#' @export
run_aquacrop_season <- function(param_values,
                         AQ, defaultpar, output_type,
                         cycle_length = cycle_length){

  AQ <- normalizePath(model_options$AQ, "/")
  #check the required initial steps
  if(!tail(str_split_1(AQ, "/"), 1) %in% c("aquacrop", "aquacrop.exe")) stop("Executable file should be aquacrop.exe (Windows) or aquacrop (Linux)")

  #if(!exists(quote(model_options$defaultpar))) stop("the default parameter file is not loaded, use the read_CRO function first")
  unlink("OUTP/*")
  # Create crop parameter file
  cycle_info <- write_CRO(as.list(param_values), defaultpar)

  situation %>%
    purrr::walk(~checkInputdata(Scenario_ = .x, cycle_info, cycle_length))

  ###########################################
  # Run Aquacrop for all the created projects

  system(model_options$AQ)

  #############
  # Read output
  results <- list.files("OUTP/", pattern = "PROseason.OUT", full.names = F) %>%
    purrr::map(\(x) readoutput_season(x)) %>%
    list_rbind()


  return(results)
}
#'


readoutput_season <- function(outputfile){
  sit_name <- gsub("PROseason.OUT", "", outputfile)
  df <- readr::read_fwf(file = paste0("OUTP/", outputfile),  skip = 4, show_col_types = F)
  names(df) <- c("RunNr", "Day", "Month", "Year",
                 "Rain","ETo","GD","CO2","Irri","Infilt","Runoff","Drain", "Upflow",
                 "E","E/Ex","Tr","TrW","Tr/Trx","SaltIn","SaltOut","SaltUp","SaltProf",
                 "Cycle","SaltStr","FertStr","WeedStr","TempStr","ExpStr","StoStr",
                 "Biomass", "Brelative","HI","Y_dry", "Y_fresh","WPet","Bin","Bout",
                 "DayN","MonthN", "YearN", "Scenario")
  df <- df %>% mutate(Scenario = sit_name)
  return(df)
}



