##################################################################
# Cropfile

# Takes a file with default values as a basis
# replaces parameter values of interest
# sets the correct number of digits to be printed in the .CRO file
# writes the .CRO file

##################################################################


write_CRO <- function(Params_select, Params_default){
  filename <-"./DATA/Crop.CRO"
  cat('Crop file generated by write_CRO function\n',
  file = filename, sep="", append=F)

  params <- Params_default %>%
    replace(list = names(Params_select), values = Params_select)

  digitvalues <- Digit_settings(params)

  write.table(digitvalues, file = filename,
              row.names = F, col.names = F,
              append = TRUE, quote = F)
  return(c(params$crop_cycle, params$cyc_d, params$mat_gdd))
}









